name = "domaincheck"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "b27527a1c72f43d686ecbfd51f70850f" # 替换成你实际的 KV ID

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
